// Современный премиальный дизайн - светлая тема с glass-эффектами
export const authStyles = {
  authContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    minHeight: '100dvh',
    padding: '20px',
    background: 'linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #f1f5f9 100%)',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  authBox: {
    background: 'rgba(255, 255, 255, 0.85)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
    padding: '40px 36px',
    borderRadius: '24px',
    boxShadow: '0 4px 24px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)',
    width: '100%',
    maxWidth: '400px',
    border: '1px solid rgba(255, 255, 255, 0.8)',
  },
  title: {
    textAlign: 'center',
    marginBottom: '6px',
    fontSize: '26px',
    fontWeight: '700',
    color: '#1e293b',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    letterSpacing: '-0.02em',
  },
  subtitle: {
    textAlign: 'center',
    marginBottom: '28px',
    fontSize: '14px',
    color: '#64748b',
    fontWeight: '400',
  },
  tabs: {
    display: 'flex',
    gap: '6px',
    marginBottom: '28px',
    background: '#f1f5f9',
    padding: '4px',
    borderRadius: '14px',
  },
  tab: {
    flex: 1,
    padding: '12px 16px',
    border: 'none',
    background: 'transparent',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '500',
    color: '#64748b',
    transition: 'all 0.2s ease',
  },
  tabActive: {
    background: '#ffffff',
    color: '#1e293b',
    boxShadow: '0 1px 3px rgba(0, 0, 0, 0.08)',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  input: {
    padding: '14px 18px',
    border: '1.5px solid #e2e8f0',
    borderRadius: '14px',
    fontSize: '15px',
    background: '#ffffff',
    color: '#1e293b',
    outline: 'none',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.02)',
  },
  inputFocus: {
    borderColor: '#3b82f6',
    boxShadow: '0 0 0 3px rgba(59, 130, 246, 0.1)',
  },
  button: {
    padding: '14px 20px',
    border: 'none',
    background: '#3b82f6',
    color: '#ffffff',
    borderRadius: '14px',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    marginTop: '8px',
    boxShadow: '0 2px 8px rgba(59, 130, 246, 0.3)',
  },
  buttonHover: {
    background: '#2563eb',
    transform: 'translateY(-1px)',
    boxShadow: '0 4px 12px rgba(59, 130, 246, 0.4)',
  },
  error: {
    color: '#dc2626',
    fontSize: '13px',
    textAlign: 'center',
    padding: '12px 16px',
    background: 'rgba(254, 226, 226, 0.8)',
    borderRadius: '12px',
    border: '1px solid rgba(252, 165, 165, 0.4)',
  },
};
